"""remove ongeki_static_music_ranking_list

Revision ID: 9c42e54a27fe
Revises: 41f77ef50588
Create Date: 2025-01-06 18:24:16.306748

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9c42e54a27fe'
down_revision = '41f77ef50588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ongeki_static_music_ranking_uk', table_name='ongeki_static_music_ranking_list')
    op.drop_table('ongeki_static_music_ranking_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ongeki_static_music_ranking_list',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('version', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('musicId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('point', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('userName', mysql.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ongeki_static_music_ranking_uk', 'ongeki_static_music_ranking_list', ['version', 'musicId'], unique=True)
    # ### end Alembic commands ###
